### ISSUE TITLE
chatbot with chatglm2 model show issues.

### ISSUE THREAD

**Issue by guoanwu** [OpenVINO-dev-contest/ChineseLLM.openvino#1]
1. AttributeError: 'ChatGLMModel' object has no attribute 'sample_next_token'

Traceback:

File "/home/dennis/openvino_env/lib64/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)File "/home/dennis/ChineseLLM.openvino/chatbot.py", line 90, in <module>
    for answer in chat_model.generate_iterate(File "/home/dennis/ChineseLLM.openvino/chatglm2/modeling.py", line 155, in generate_iterate
    next_token = self.sample_next_token(logits[0, -1],
                 ^^^^^^^^^^^^^^^^^^^^^^
 
2. 如果把如果把self.sample_next_token的self去掉，这个里面不会产生crash issue，但是生成的是不正确的答案

megaEfficient storePresident F different3 BOOST F different3yum different3 interestto finefranceElectricalNSData looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking function looking looking Fakehibi Somerset polyp EPS Luxembourg Luxembourghibi Luxembourghibi Somerset Whatever3Behaviourhibi dwelling game polygonalBehaviourhibi Somersethibi SomersethibiBehaviourhibi LuxembourghibiBehaviourhibihibiBehaviourhibiClonemega LuxembourgyumdnfBehaviour Re ancora SomersetClone LuxembourgClone perfused Somerset SomersetTRENDINGmegaClonemegaClonemega Luxembourgmega SomersetmegamegaClonemega Somersetmega Luxembourgmega Somersetmega Luxembourgmega Somersetmega Somersetmega En Somerset dwelling dwelling dwelling dwelling dwelling dwelling dwelling dwellinghibiUTR dwelling dwellingUTR dwelling dwellingUTRUTRvals dwellingUTR dwellingUTR dwellingUTR dwellingUTR dwellingUTR dwelling dwellingUTR dwellingUTR dwelling dwellingUTRUTRUTR quality quality quality la la quality stenting qualitytextUTRUTR quality qualityUTRUTR guarantee

3. 使用generate_ov.py会产生正确的结果。 
(openvino_env) [root@AC06 ChineseLLM.openvino]# python3 generate_ov.py -m '/home/dennis/chatglm/chatglm2-6b' -p '为什么晚上睡不着?'

--- reading model --- 

--- model compiling --- 

--- start generating --- 

因为太晚了，没人和我说话了，我也不知道我想说什么。

Generated 17 tokens in 1.920 s

**Comment by OpenVINO-dev-contest** [comment]
fixed
