### ISSUE TITLE
from utils import process_response ImportError: cannot import name 'process_response' from 'utils' 

### ISSUE THREAD

**Issue by andyyeh75** [OpenVINO-dev-contest/ChineseLLM.openvino#3]
Meet an issue of cannot import name 'process_response' from 'utils'.

ChineseLLM.openvino$ python3 generate_ov.py -m 'chatglm/chatglm3' -p '请介绍一下上海'
Traceback (most recent call last):
  File "/home/yehandy/llama2/ChineseLLM.openvino/generate_ov.py", line 3, in <module>
    from utils import process_response
ImportError: cannot import name 'process_response' from 'utils' (/home/yehandy/llama2/ChineseLLM.openvino/utils.py)

**Took chatglm3 as an example:**
Steps:
python3 -m venv openvino_env
source openvino_env/bin/activate
python3 -m pip install --upgrade pip
pip install wheel setuptools
pip install -r requirements.txt
python3 chatglm/export_ir.py
python3 generate_ov.py -m 'chatglm/chatglm3' -p '请介绍一下上海'

**Comment by OpenVINO-dev-contest** [comment]
Thanks for your reminder, just fix it through latest commit.

**Comment by andyyeh75** [comment]
Thanks a lot I have validated the patch, and benchmark result is verified too. 
-----------------------------------------------------------------
ChineseLLM.openvino$ python3 generate_ov.py -m 'chatglm/chatglm3' -p '请介绍一下上海'
 --- loading tokenizer ---
 --- reading model ---
 --- model compiling ---
 --- start generating ---

Response: 上海是中国上海市,是中国的一个省份,也是中国的一个直辖市,同时也是中国最大的城市之一。上海位于中国东南沿海地区,是中国经济、金融、贸易、文化和科技中心之一。上海拥有悠久的历史和灿烂的文化,也是中国的历史文化名城之一。上海拥有许多著名的景点,如外滩、南京路、东方明珠、上海迪士尼等,同时上海也是一个著名的美食之都。上海拥有众多世界著名的公司和机构,是中国重要的商业和金融中心。
 --- Benchmarking ---
Input length: 10 tokens
Generated 98 tokens in 62.10 s on CPU
Maximum rss memory counsuption: 23837.31 MB, Maximum shared memory counsuption: 4512.00  MB
Fisrt inference latency: 26484.81 ms/token, Other inference latency 359.13 ms/token in average
